LiquidityEngineService:
  Name: Default
  
  WalletId:
    settings-key: LiquidityEngineService-WalletId

  AssetsCacheExpirationPeriod: 00:10:00
  
  Db:
    DataConnectionString:
      settings-key: LiquidityEngineService-DataConnectionString
      types:
      - AzureTableStorage

    LogsConnectionString:
      settings-key: LiquidityEngineService-LogsConnectionString
      types:
      - AzureTableStorage
  
  Rabbit:
    Subscribers:
      LykkeTrades:
        ConnectionString:
          settings-key: LiquidityEngineService-Rabbit-Subscribers-LykkeTrades-ConnectionString
          types:
          - RabbitMq
        Exchange:
          settings-key: LiquidityEngineService-Rabbit-Subscribers-LykkeTrades-Exchange
        Queue:
          settings-key: LiquidityEngineService-Rabbit-Subscribers-LykkeTrades-Queue

      RawPriceRabbitMq:
        ConnectionString:
          settings-key: LiquidityEngineService-Rabbit-Subscribers-RawPriceRabbitMq-ConnectionString
          types:
          - RabbitMq
        Exchange:
          settings-key: LiquidityEngineService-Rabbit-Subscribers-RawPriceRabbitMq-Exchange
        Queue:
          settings-key: LiquidityEngineService-Rabbit-Subscribers-RawPriceRabbitMq-Queue

B2C2Client:
  Url:
    settings-key: B2C2AdapterUrl
  AuthorizationToken:
    settings-key: LiquidityEngineService-B2C2Client-AuthorizationToken
    
AssetsServiceClient:
  ServiceUrl:
    settings-key: AssetsServiceUrl
    
BalancesServiceClient:
  ServiceUrl:
    settings-key: BalancesServiceUrl
    
ExchangeOperationsServiceClient:
  ServiceUrl:
    settings-key: ExchangeOperationsServiceUrl

MatchingEngineClient:
  IpEndpoint:
    Port:
      settings-key: MatchingEngine-Port
    Host:
      settings-key: MatchingEngine-Host
      
SlackNotifications:
  AzureQueue:
    ConnectionString:
      settings-key: SlackNotificationsConnString
      types:
      - AzureTableStorage
    QueueName:
      settings-key: SlackQueueName

MonitoringServiceClient:
  MonitoringServiceUrl:
    settings-key: MonitoringServiceUrl