LiquidityEngineService:
  Name: Default

  WalletId:
    settings-key: LiquidityEngineService-WalletId

  AssetsCacheExpirationPeriod: 00:10:00

  Db:
    PostgresConnectionString:
      settings-key: LiquidityEngineService-PostgresConnectionString
      
    DataConnectionString:
      settings-key: LiquidityEngineService-DataConnectionString
      types:
      - AzureTableStorage

    LogsConnectionString:
      settings-key: LiquidityEngineService-LogsConnectionString
      types:
      - AzureTableStorage
      
    LykkeTradesMeQueuesDeduplicatorConnectionString:
      settings-key: LiquidityEngineService-LykkeTradesMeQueuesDeduplicatorConnectionString
      types:
      - AzureTableStorage

  Rabbit:
    Subscribers:
      LykkeTrades:
        ConnectionString:
          settings-key: MatchingEngineRabbitMqConnectionString
          types:
          - RabbitMq
        AlternateConnectionString:
          settings-key: AlternateMatchingEngineRabbitMqConnectionString
          types:
          - RabbitMq
        Exchange:
          settings-key: MatchingEngineSpotEventsExchange
        Queue:
          settings-key: LiquidityEngineService-Rabbit-Subscribers-LykkeTrades-Queue

      B2C2Quotes:
        ConnectionString:
          settings-key: RawPriceRabbitMq
          types:
          - RabbitMq
        Exchange:
          settings-key: LiquidityEngineService-Rabbit-Subscribers-B2C2Quotes-Exchange
        Queue:
          settings-key: LiquidityEngineService-Rabbit-Subscribers-B2C2Quotes-Queue

      B2C2OrderBooks:
        ConnectionString:
          settings-key: RawPriceRabbitMq
          types:
          - RabbitMq
        Exchange:
          settings-key: LiquidityEngineService-Rabbit-Subscribers-B2C2OrderBooks-Exchange
        Queue:
          settings-key: LiquidityEngineService-Rabbit-Subscribers-B2C2OrderBooks-Queue

      Quotes:
        ConnectionString:
          settings-key: RawPriceRabbitMq
          types:
          - RabbitMq
        Exchanges:
          settings-key: LiquidityEngineService-Rabbit-Subscribers-Quotes-Exchanges
          types:
          - JsonArray
        Queue:
          settings-key: LiquidityEngineService-Rabbit-Subscribers-Quotes-Queue

  Dwh:
    DatabaseName:
      settings-key: LiquidityEngineService-DwhSettings-DatabaseName
    StoredProcedures:
      Trades:
        settings-key: LiquidityEngineService-DwhSettings-StoredProcedures-Trades

B2C2Client:
  Url:
    settings-key: B2C2AdapterUrl
  AuthorizationToken:
    settings-key: LiquidityEngineService-B2C2Client-AuthorizationToken

AssetsServiceClient:
  ServiceUrl:
    settings-key: AssetsServiceUrl

BalancesServiceClient:
  ServiceUrl:
    settings-key: BalancesServiceUrl

ExchangeOperationsServiceClient:
  ServiceUrl:
    settings-key: ExchangeOperationsServiceUrl

DwhServiceClient:
  ServiceUrl:
    settings-key: DwhServiceUrl

MatchingEngineClient:
  IpEndpoint:
    Port:
      settings-key: MatchingEngine-Port
    Host:
      settings-key: MatchingEngine-Host

SlackNotifications:
  AzureQueue:
    ConnectionString:
      settings-key: SlackNotificationsConnString
      types:
      - AzureTableStorage
    QueueName:
      settings-key: SlackQueueName

MonitoringServiceClient:
  MonitoringServiceUrl:
    settings-key: MonitoringServiceUrl